export const CONTENT_TYPES = [
  "character_assessment_line",
  "current_state",
  "what_changed",
  "recent_observation",
  "new_discovery",
  "known_fact_candidate",
  "archetype_shift",
  "meter_shift",
  "canon_callback",
  "ambient_life",
  "status_line",
  "explanation_line",
] as const;

export type ContentType = (typeof CONTENT_TYPES)[number];

export const EVENT_FAMILIES = [
  "gambling_win",
  "gambling_loss",
  "gambling_heavy_activity",
  "church_donation",
  "money_gain",
  "money_loss",
  "hospital",
  "jail",
  "crime_streak",
  "travel",
  "racing",
  "education",
  "company_work",
  "faction_activity",
  "rehab",
  "drug_use",
  "quiet_day",
  "no_meaningful_change",
  "canon_callback",
  "archetype_emergence",
  "relationship_decay",
  "reputation_shift",
  "debt_shift",
  "vice_shift",
  "luck_shift",
  "heat_shift",
  "rot_shift",
  "rep_shift",
  "first_observation",
  "assessment",
  "lock_batch",
] as const;

export type EventFamily = (typeof EVENT_FAMILIES)[number];

export const RARITY_WEIGHT_MOD: Record<string, number> = {
  common: 0,
  uncommon: 8,
  rare: 15,
  legendary: 25,
};

/** Broader fallbacks when exact event_family has no matches */
export const EVENT_FAMILY_FALLBACKS: Record<string, string[]> = {
  gambling_win: ["gambling_heavy_activity", "money_gain", "quiet_day"],
  gambling_loss: ["gambling_heavy_activity", "money_loss", "quiet_day"],
  gambling_heavy_activity: ["vice_shift", "quiet_day"],
  church_donation: ["quiet_day", "reputation_shift"],
  money_gain: ["quiet_day", "reputation_shift"],
  money_loss: ["debt_shift", "quiet_day"],
  hospital: ["quiet_day"],
  jail: ["crime_streak", "heat_shift"],
  crime_streak: ["heat_shift", "vice_shift"],
  travel: ["quiet_day"],
  drug_use: ["vice_shift", "rehab"],
  quiet_day: ["no_meaningful_change", "ambient_life"],
  no_meaningful_change: ["ambient_life"],
  first_observation: ["assessment", "quiet_day"],
  assessment: ["first_observation", "quiet_day"],
  lock_batch: ["ambient_life", "quiet_day"],
};

export const FIELD_TO_EVENT: Record<string, EventFamily> = {
  hospital: "hospital",
  jailed: "jail",
  criminaloffenses: "crime_streak",
  traveltimes: "travel",
  travelDestination: "travel",
  drugs: "drug_use",
  alcoholused: "vice_shift",
  donations: "church_donation",
  networth: "money_gain",
  moneyonhand: "money_gain",
  factionId: "faction_activity",
  job: "company_work",
  jobPosition: "company_work",
  education: "education",
  attackswon: "reputation_shift",
  level: "reputation_shift",
};

export const CALIBRATION_TAG_MAP: Record<string, { block?: string[]; prefer?: string[] }> = {
  "Too violent": { block: ["violent", "grim"], prefer: ["mundane"] },
  "Too goofy": { block: ["funny", "absurd"], prefer: ["noir", "mundane"] },
  "Too clean": { block: ["mundane"], prefer: ["grim", "vice"] },
  "Too pathetic": { block: ["pathetic"], prefer: ["professional"] },
  "Too rich": { block: ["rich", "wealth"], prefer: ["broke", "debt"] },
  "Too evil": { block: ["violent", "grim"], prefer: ["careful", "nonviolent"] },
  "More tragic": { prefer: ["grim", "noir"] },
  "More funny": { prefer: ["funny"] },
  "More noir": { prefer: ["noir", "grim"] },
  "More mundane": { prefer: ["mundane"] },
  "More criminal": { prefer: ["crime", "heat", "reckless"] },
  "Less criminal": { block: ["crime", "heat"], prefer: ["careful", "nonviolent"] },
  "More pathetic": { prefer: ["pathetic", "washed_up"] },
  "Less pathetic": { block: ["pathetic", "washed_up"] },
  "More grounded": { prefer: ["mundane", "professional"] },
  "Less edgy": { block: ["grim", "violent"], prefer: ["mundane"] },
  "More washed-up": { prefer: ["washed_up", "pathetic"] },
  "More competent": { prefer: ["professional", "careful"], block: ["pathetic"] },
};

export const FEEDBACK_TAG_MAP: Record<string, { block?: string[]; prefer?: string[] }> = {
  "Too violent": { block: ["violent", "grim"] },
  "Too silly": { block: ["funny", "absurd"] },
  "Too edgy": { block: ["grim", "violent"] },
  "Too boring": { block: ["mundane"] },
  "Too clean": { block: ["mundane"] },
  "Too mean": { block: ["mean", "grim"] },
  "Too random": { block: ["absurd"] },
  "Too dramatic": { block: ["grim"] },
  "Too generic": { block: ["mundane"] },
  "More like this": {},
  "Less like this": {},
  "Make it darker": { prefer: ["noir", "grim"] },
  "Make it funnier": { prefer: ["funny"] },
  "Make it more mundane": { prefer: ["mundane"] },
  "Never reference this again": {},
};
